### ISSUE TITLE
Unable to view all files after any category is selected in ShareActivity

### ISSUE THREAD

**Issue by archie94** [sunny5125/pdm#18]

**Comment by namanmehta1997** [comment]
@archie94  Please shed some more lights

**Comment by archie94** [comment]
I do not remember exactly but I think you cannot view all files after you have filtered them by category.

**Comment by sunysaurav** [comment]
@archie94  i think this was ui issue ...unable to view all kind of file in chat adapter.

**Comment by archie94** [comment]
We should not build the UI from scratch anyway. So @namanmehta1997 you may ignore this.
